[[plugins]]
  package = "netlify-plugin-bundle-env"
  config = { source = "src" }

[build]
  publish = ".dist"
  command = "npm run build"
# netlify.toml
[build.environment]
  VARIABLE = "root"
[[plugins]]
package = "netlify-plugin-check-output-for-puppy-references"
  [plugins.inputs]
  breeds = ["pomeranian", "chihuahua", "bulldog"]

[[redirects]]
  from = "https://lescoffee.shop/"
  to = "https://lescoffee.com"
  status = 301
  force = true

